import { supabase } from '../utils/supabase';
import { getLocalDeals, getLocalCustomers, getLocalActivities, endLocalTrial, isLocalTrialActive } from './localDb';

export const migrateLocalToSupabase = async (userId) => {
  if (!userId || !isLocalTrialActive()) return { success: false, message: 'No local trial active or no user id' };

  try {
    const deals = getLocalDeals();
    const customers = getLocalCustomers();
    const activities = getLocalActivities();

    console.log('Migrating local data to Supabase...', { deals, customers, activities });

    // Ensure IDs are generated by Supabase (uuid) or keep them if they are uuid.
    // Our local ids are 'deal-xxx', 'cust-xxx'. We should strip the ID so Supabase generates new UUIDs, 
    // BUT we need to map deal_id and customer_id! 
    // This could be complicated. Instead, we can just let them stay as string IDs if our DB accepts string IDs?
    // Wait, Supabase `id` for deals is usually `uuid`. Our local ones are strings. 
    // Let's check `apiDeals.js` how deals are added.
    
    // For a simple world-class trial, we'll just skip the complex mapping for now, 
    // or map them properly:

    // 1. Customers
    const customerIdMap = {}; // old -> new
    for (const c of customers) {
      const oldId = c.id;
      const newCustomer = {
        ...c,
        owner_id: userId,
      };
      delete newCustomer.id; // Let supabase generate UUID

      const { data, error } = await supabase.from('customers').insert(newCustomer).select().single();
      if (!error && data) {
        customerIdMap[oldId] = data.id;
      }
    }

    // 2. Deals
    const dealIdMap = {}; // old -> new
    for (const d of deals) {
      const oldId = d.id;
      const newDeal = {
        ...d,
        owner_id: userId,
        customer_id: d.customer_id ? (customerIdMap[d.customer_id] || null) : null,
      };
      delete newDeal.id;

      const { data, error } = await supabase.from('deals').insert(newDeal).select().single();
      if (!error && data) {
        dealIdMap[oldId] = data.id;
      }
    }

    // 3. Activities
    for (const a of activities) {
      const newActivity = {
        ...a,
        owner_id: userId,
        deal_id: a.deal_id ? (dealIdMap[a.deal_id] || null) : null,
        // if we had customer_id in activities we would map it too
      };
      delete newActivity.id;

      await supabase.from('activities').insert(newActivity);
    }

    // Clean up local trial
    endLocalTrial();
    
    return { success: true };
  } catch (err) {
    console.error('Migration failed:', err);
    return { success: false, error: err };
  }
};
